In [ ]:
import numpy as np

np.zeros((3,3))
np.ones((2,3))
np.eye(5)
np.full((4,5),78)
np.arange(1,99,17)
np.linspace(0,1,6)


array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [3]:
import numpy as np
my_arr = np.array(([1,2,3],[2,4,6],[3,6,9],[4,8,12]))
my_arr

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [4]:
my_arr.flatten()

array([ 1,  2,  3,  2,  4,  6,  3,  6,  9,  4,  8, 12])

In [6]:
my_arr.shape

(4, 3)

In [7]:
my_arr.size

12

In [8]:
my_arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 2],
       [ 4],
       [ 6],
       [ 3],
       [ 6],
       [ 9],
       [ 4],
       [ 8],
       [12]])

In [10]:
my_arr.reshape(3,4)

array([[ 1,  2,  3,  2],
       [ 4,  6,  3,  6],
       [ 9,  4,  8, 12]])

In [13]:
my_arr.ndim

2

In [14]:
my_arr.dtype

dtype('int64')