In [5]:
import numpy as np

arr = np.array([[1,2,3],[2,3,4],[4,5,6],[6,7,8]])
arr
print(arr)
flat = arr.flatten()
print(flat)

print(flat[0])
print(flat[-1])
print(flat[:4])
print(flat[::-1])
print(flat[::2])


[[1 2 3]
 [2 3 4]
 [4 5 6]
 [6 7 8]]
[1 2 3 2 3 4 4 5 6 6 7 8]
1
8
[1 2 3 2]
[8 7 6 6 5 4 4 3 2 3 2 1]
[1 3 3 4 6 7]


In [6]:
idx = [1,5,3]
print(flat[idx])

[2 4 2]


In [8]:
mask = flat>5
print(flat[mask])

[6 6 7 8]


In [ ]:
arr = np.zeros(3)
print(arr)
arr2 = np.ones(3)
print(arr2)

myarr2 = np.array([1,2,3,5,4,2,34,5,67])
print(myarr2)

print(myarr2.reshape(3,3))

great = myarr2>50
idx = [1,4,3]
print(myarr2[idx]) # fancy indexing

print(myarr2[great])   #boolean masking



[0. 0. 0.]
[1. 1. 1.]
[ 1  2  3  5  4  2 34  5 67]
[[ 1  2  3]
 [ 5  4  2]
 [34  5 67]]
[2 4 5]
[67]
