In [2]:
import numpy as np

# Indexing same as python

arr = np.array([1,2,3,4])
print(arr[1],end=" ")
print(arr[0])

2 1


In [10]:
# slicing extracting parts of an array
arr = np.array([10,20,30,40,50])
sliced_array = arr[1:4]
print(sliced_array)
sl_arr = arr[:3]
print(sl_arr)
sl_arr2 = arr[::2].copy()
print(sl_arr2)
sl_arr2[1] = 999
print(arr)

[20 30 40]
[10 20 30]
[10 30 50]
[10 20 30 40 50]


In [16]:
# Fancy indexing and boolean masking
arr = np.array([10,20,30,40,50])
idx = [0,2,4]
print(arr[idx])
mask = arr>25
print(arr[mask])


[10 30 50]
[30 40 50]
