In [5]:
import numpy as np
arr = np.array([x for x in range(10,101)])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
(91,)
1
91


In [15]:
import time
l1 = [x for x in range(10000)]
l2 = [x for  x in range(10000)]
start = time.time()
l3 = [a*b for a in l1 for b in l2]
end = time.time()
print(end-start)

4.701039552688599


In [14]:
arr = np.array([x for x in range(10000)])
arr2 = np.array([x for x in range(10000)])
start = time.time()
arr3 = arr[:,None]*arr2
end = time.time()
print(end-start)

0.5566771030426025


In [18]:
arr = np.array(x for x in range(1000000))
print(arr.nbytes)
print(arr.dtype)
print(type(arr))

8
object
<class 'numpy.ndarray'>


In [25]:
# # numpy lecture 3
# Exercises for Practice
# Create a 3×3 array filled with random numbers and print its shape.
# Convert an array of floats [1.1, 2.2, 3.3] into integers.
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
# Reshape a 1D array of size 9 into a 3×3 matrix.
# Use boolean masking to filter numbers greater than 50 in an array.

import random as rd
import numpy as np

#1.
arr = np.random.uniform(0,100,(3,3))
print(arr.shape)
arr = np.random.randint(0,10,(3,4))
print(arr.shape)

#2.
arr2 = np.array([1.1,2.2,3.3],dtype="float32")
print(arr2.dtype)
print(arr2)
arr2 = arr2.astype("int32")
print(arr2.dtype)
print(arr2)

#3.
arr3 = np.array([1, 2, 3, 4, 5, 6])
evenarr = arr3%2 == 0
print(arr3[evenarr])

#4.
arr4 = np.random.randint(0,9,(9))
print(arr4)
#arr4.reshape(3,3)
print(arr4.reshape(3,3))

#5.
arr5 = np.random.uniform(20,80,(3,4))
print(arr5.shape)
print(arr5)
print(arr5[arr5>50])


(3, 3)
(3, 4)
float32
[1.1 2.2 3.3]
int32
[1 2 3]
[2 4 6]
[0 2 7 8 1 1 3 8 1]
[[0 2 7]
 [8 1 1]
 [3 8 1]]
(3, 4)
[[55.75576399 74.24943528 23.93032039 59.12488933]
 [31.51191545 64.66326192 62.0230517  42.07806923]
 [73.28895512 24.54746741 55.34387564 41.22642949]]
[55.75576399 74.24943528 59.12488933 64.66326192 62.0230517  73.28895512
 55.34387564]
