rray Indexing & Slicing

Extract the first 3 elements of a NumPy array [10, 20, 30, 40, 50].

Reverse a NumPy array [1, 2, 3, 4, 5].

Given arr = np.array([5, 10, 15, 20, 25]), how do you extract the elements [10, 20]?

For a 2D array [[1,2,3],[4,5,6],[7,8,9]], extract the element 6.

For the same array, extract the entire second row.

In [18]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[:3])
print(*reversed(arr))
arr3 = np.array([5, 10, 15, 20, 25])
arr2 = [x for x in arr3 if x%10 ==0]
print(*arr2)
arr4 = [[1,2,3],[4,5,6],[7,8,9]]
print(arr4[1][2])
print(arr4[1:2])


[10 20 30]
50 40 30 20 10
10 20
6
[[4, 5, 6]]


Array Operations

Create two arrays [1,2,3] and [4,5,6]. Add, subtract, and multiply them element-wise.

Given arr = np.array([1, 2, 3, 4, 5]), square every element.

Find the maximum and minimum values in arr = np.array([3, 7, 2, 9, 4]).

Find the sum of all elements in a NumPy array [1, 2, 3, 4, 5].

Calculate the mean and standard deviation of [10, 20, 30, 40, 50].

In [29]:
arr1 = np.array([1,2,3])
arr2 =np.array([4,5,6])
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)

print("Square number: ")
arr = np.array([1, 2, 3, 4, 5])
print("Sum = ", sum(arr))
arr = arr**2
print(arr)

arr = np.array([3, 7, 2, 9, 4])
print(max(arr))
print(min(arr))

arr = np.array([10, 20, 30, 40, 50])
print(np.mean(arr))
print(np.std(arr))



[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
Square number: 
Sum =  15
[ 1  4  9 16 25]
9
2
30.0
14.142135623730951


Reshaping & Combining

Convert a 1D array of 12 elements into a 3 × 4 2D array.

Stack two arrays [1,2,3] and [4,5,6] vertically and horizontally.

Flatten a 2D array [[1,2],[3,4]] into a 1D array.

In [41]:
arr = np.array([x for x in range(1,13)])
print(arr)
print(arr.reshape(3,4))
print(arr)

arr = np.array( [[1,2],[3,4]])
print(arr.flatten())

arr = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.stack((arr,arr2),axis = 0))
print(np.stack((arr,arr2),axis = 1))

print(np.vstack((arr,arr2)))
print(np.hstack((arr,arr2)))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Boolean Indexing

Given arr = np.array([10, 15, 20, 25, 30]), extract elements greater than 20.

Replace all odd numbers in [1,2,3,4,5,6] with -1.

In [45]:
arr = np.array([10, 15, 20, 25, 30])
x = arr>20
print(arr[x])

arr = np.array([1,2,3,4,5,6])
arr[arr%2!=0] = -1
print(arr)


[25 30]
[-1  2 -1  4 -1  6]
